### PR TITLE
Make changes for program stability

### PR DESCRIPTION
**Pull request by hamidreza01**
You should not throw an error for the absence of a user in the program, so a user may not exist or disappear for any reason.. this is not an error, it should not cause an error to be thrown.

### CODE REVIEW

**Comment by Mahdikhoubrouy** [comment]
hey bro this is not good..

**Comment by hamidreza01** [comment]
khak to saret mehdi, heif vaght 😂😂

**Comment by Mahdikhoubrouy** [comment]
> khak to saret mehdi, heif vaght 😂😂

dash khodam osgol nistam mitonestam intor benivisam

**Comment by hamidreza01** [comment]
> > khak to saret mehdi, heif vaght 😂😂
> 
> dash khodam osgol nistam mitonestam intor benivisam

Boro Boro ke in dast namak nadare 🤣

**Pull request closed without merging**
